### ISSUE TITLE
Static connection isn't working with DBAL MasterSlaveConnection

### ISSUE THREAD

**Issue by andrew287** [dmaicher/doctrine-test-bundle#106]
I use DBAL MasterSlaveConnection in my project. After update to 6.3.0 version if `enable_static_connection: true` I get an error:  `Did not find key "dama.connection_name" inside connection params.`

What am I missing?

**Comment by dmaicher** [comment]
Can you try release `6.2.1` instead of `6.3.0`?

**Comment by Groonya** [comment]
Yes, 6.2.1 works perfectly.

**Comment by dmaicher** [comment]
Ok thanks for the info. I will try to reproduce this and provide a fix

**Comment by dmaicher** [comment]
@Groonya I was able to reproduce it. Can you confirm this fix works?

https://github.com/dmaicher/doctrine-test-bundle/pull/107/files

**Comment by Groonya** [comment]
So fast:)
There are no any errors anymore, thanks!

**Comment by dmaicher** [comment]
New release tagged: https://github.com/dmaicher/doctrine-test-bundle/releases/tag/v6.3.1
