### ISSUE TITLE
Minor annoyances

### ISSUE THREAD

**Issue by garak** [dmaicher/doctrine-test-bundle#11]
My scenario (I think it's a pretty common one): I'm using a separate database for tests , e.g. `mydb` and `mydb_test`.
When the bundle is enabled, I'm not able to re-create the test database anymore (after dropping it, of course).
The error is `SQLSTATE[42000] [1049] Unknown database 'mydb_test'`
I'm forced to temporary comment out the bundle fro AppKernel.
The same applies for fixtures loading: without commenting the bundle, trying to load new fixtures is impossible, like if they're cached.

**Comment by dmaicher** [comment]
I'm using the same approach so I'm not quite sure why this is happening for you.

Where/how do you create the database and load the fixtures? In the PHPUnit bootstrap? Before?

**Comment by garak** [comment]
I do everything with console commands.
So, db creation is done via `bin/console do:da:cr -e=test` and fixtures loading via `bin/console do:fi:lo -e=test -n`

**Comment by dmaicher** [comment]
Will try to reproduce this ;)

**Comment by dmaicher** [comment]
I'm basically executing the symfony commands from within my PHPUnit bootstrap so they all run inside the same php process.

**Comment by garak** [comment]
Can you provide an example?

**Comment by dmaicher** [comment]
I basically use a custom php bootstrap for phpunit:

```xml
<phpunit
    ...
    bootstrap = "phpunit.bootstrap.php">
```

And in that file I boot up a Symfony Kernel and just execute some commands:

```php
<?php
require_once __DIR__.'/bootstrap.php.cache';

$_ENV['SF_DEBUG'] = true;

if(getenv('SF_DEBUG') !== false) {
    $_ENV['SF_DEBUG'] = (bool) getenv('SF_DEBUG');
}

$kernel = new AppKernel('test', $_ENV['SF_DEBUG']); 
$kernel->boot();

$application = new Application($kernel);
$application->setAutoExit(false);

$runCommand = function (\Symfony\Component\Console\Command\Command $command, $options = []) use ($application) {
    $application->add($command);
    $output = new ConsoleOutput();
    $options['command'] = $command->getName();
    $options['--env'] = 'test';
    if (!$application->getKernel()->isDebug()) {
        $options['--no-debug'] = true;
    }
    if (isset($options['no-output']) && $options['no-output']) {
        unset($options['no-output']);
        $output = new NullOutput();
    }

    $input = new ArrayInput($options);
    $input->setInteractive(false);

    $command->run($input, $output);
};

$runCommand(new DropDatabaseDoctrineCommand(), [
    '--force' => true
]);

$runCommand(new CreateDatabaseDoctrineCommand());

$runCommand(new CreateSchemaDoctrineCommand());

$runCommand(new LoadDataFixturesDoctrineCommand(), [
    '--append' => true,
]);

**Comment by dmaicher** [comment]
But anyway I have the same issue when my test database initially does not exist ;)
So I can reproduce the problem and I think I know the cause. Will let you know later.

**Comment by garak** [comment]
You're awesome!

**Comment by dmaicher** [comment]
Fix is in master branch. Can you give it a try? For me it solves the issue :smile:

**Comment by garak** [comment]
Excellent! Thank you
