### ISSUE TITLE
TypeError : Return value of DAMA\DoctrineTestBundle\Doctrine\DBAL\StaticDriver::getDatabase() must be of the type string, null returned

### ISSUE THREAD

**Issue by klodoma** [dmaicher/doctrine-test-bundle#114]
```
<?php

namespace DAMA\DoctrineTestBundle\Doctrine\DBAL;

class StaticDriver implements Driver, ExceptionConverterDriver, VersionAwarePlatformDriver

    /**
     * {@inheritdoc}
     */
    public function getDatabase(\Doctrine\DBAL\Connection $conn): string
    {
        return $this->underlyingDriver->getDatabase($conn);
    }

```

If you use an in-memory database
`<env name="DATABASE_URL" value="sqlite:///:memory:"/>`

then this leads to a type error:

`TypeError : Return value of DAMA\DoctrineTestBundle\Doctrine\DBAL\StaticDriver::getDatabase() must be of the type string, null returned`

A in memory sqlite goes in here and returns NULL and not string(has no path)
```

    /**
     * {@inheritdoc}
     */
    public function getDatabase(Connection $conn)
    {
        $params = $conn->getParams();

        return $params['path'] ?? null;
    }

```

Just changing 

> public function getDatabase(\Doctrine\DBAL\Connection $conn): ?string

 fixes the issue.

**Comment by dmaicher** [comment]
See https://github.com/dmaicher/doctrine-test-bundle/pull/115

Indeed the `AbstractSQLiteDriver` may return `null` although the phpdoc annotates the method with return type `string` on the `Driver` interface :confused: 

https://github.com/doctrine/dbal/blob/2.11.x/lib/Doctrine/DBAL/Driver.php#L56

**Comment by dmaicher** [comment]
new release 6.3.2 tagged :wink:

**Comment by klodoma** [comment]
Thank you!
