### ISSUE TITLE
phpunit very slow

### ISSUE THREAD

**Issue by DanielCambray** [dmaicher/doctrine-test-bundle#118]
Hi,

sorry if it's a stupid question. I have about 150 tests that run rather quickly (about 5s). But when I set the parameter enable_static_connection to true, it become very sluggish (about 1min). Have I miss something ?

Thanks.

**Comment by dmaicher** [comment]
Hard to tell what's happening there in your case. Can you share a blackfire profile comparison of both cases maybe?

**Comment by dmaicher** [comment]
Closing for now. Let me know if you have any way for me to profile those slow tests.
