### ISSUE TITLE
Integration with @depends

### ISSUE THREAD

**Issue by mareckigit** [dmaicher/doctrine-test-bundle#119]
Is it possible to integrate the bundle with PHPUnit tests dependencies? 
I mean sth like this:
```php
class MyTests 
{
    public function testOne()
    {
        // do changes in DB
    }

    /**
     * @depends testOne
     */
    public function testTwo()
    {
        // do sth with data created in testOne()
    }
}
```

**Comment by dmaicher** [comment]
Thanks for the proposal but I personally don't think this is a good idea. Tests should be isolated from each other. If two tests depend on each other then I would combine them into one test or have some shared code between them.

**Comment by mareckigit** [comment]
> One unit test usually covers one specific path in one function or method. However a test method is not necessarily an encapsulated, independent entity. Often there are implicit dependencies between test methods, hidden in the implementation scenario of a test.

Consider the UserController. There is a registerAction() and confirmAction(). Consequently, there are 2 separate tests testRegisterAction() and testConfirmAction(). Can't execute testConfirmAction() if there is no data created by testRegisterAction().

I agree with - tests should be isolated from each other, but if we mean paths. The testArticleView() should not depend on testArticleCreate(). It should use data loaded by fixtures. If testArticleCreate() returns failure, it doesn't mean that article view is not working and testArticleView() should return success.
