### ISSUE TITLE
There is already an active transaction

### ISSUE THREAD

**Issue by mareckigit** [dmaicher/doctrine-test-bundle#120]
When I use: 
`./bin/phpunit --group mygroup`
I get exception: There is already an active transaction

When I use:
`./bin/phpunit`
it works.

Before installation of doctrine-test-bundle both cases worked correctly.

**Comment by dmaicher** [comment]
- Can I see a stack trace of that exception? 
- Are you doing any database things inside `setUpBeforeClass` methods?

**Comment by mareckigit** [comment]
I simulate authethication in setUpBeforeClass(). When it's moved to single test, it works.

```
PDOException {#1263
  #message: "There is already an active transaction"
  #code: 0
  #file: "./vendor/dama/doctrine-test-bundle/src/DAMA/DoctrineTestBundle/Doctrine/DBAL/StaticDriver.php"
  #line: 126
  +errorInfo: null
  trace: {
    ./vendor/dama/doctrine-test-bundle/src/DAMA/DoctrineTestBundle/Doctrine/DBAL/StaticDriver.php:126 { …}
    ./vendor/dama/doctrine-test-bundle/src/DAMA/DoctrineTestBundle/PHPUnit/PHPUnitExtension.php:20 { …}
    ./bin/.phpunit/phpunit-7.5-0/src/Runner/Hook/TestListenerAdapter.php:40 {
      PHPUnit\Runner\TestListenerAdapter->startTest(Test $test): void^
      › if ($hook instanceof BeforeTestHook) {
      ›     $hook->executeBeforeTest(TestUtil::describeAsString($test));
      › }
    }
    ./bin/.phpunit/phpunit-7.5-0/src/Framework/TestResult.php:406 { …}
    ./bin/.phpunit/phpunit-7.5-0/src/Framework/TestResult.php:626 { …}
    ./bin/.phpunit/phpunit-7.5-0/src/Framework/TestCase.php:797 { …}
    ./bin/.phpunit/phpunit-7.5-0/src/Framework/TestSuite.php:746 { …}
    ./bin/.phpunit/phpunit-7.5-0/src/Framework/TestSuite.php:746 { …}
    ./bin/.phpunit/phpunit-7.5-0/src/Framework/TestSuite.php:746 { …}
    ./bin/.phpunit/phpunit-7.5-0/src/TextUI/TestRunner.php:652 { …}
    ./bin/.phpunit/phpunit-7.5-0/src/TextUI/Command.php:206 { …}
    ./bin/.phpunit/phpunit-7.5-0/src/TextUI/Command.php:162 { …}
    ./bin/.phpunit/phpunit-7.5-0/phpunit:18 { …}
    ./vendor/symfony/phpunit-bridge/bin/simple-phpunit.php:344 { …}
    ./bin/phpunit:13 { …}
  }
}

```

**Comment by dmaicher** [comment]
Currently there is no way to support that unfortunately :cry: 

See https://github.com/dmaicher/doctrine-test-bundle/issues/108

The `BeforeTestHook` this bundle uses is executed after the `setUpBeforeClass` so all changes done there are not transactional anymore and there is no way to roll them back.

**Comment by mareckigit** [comment]
Sorry, I haven't seen this issue. I've added  `StaticDriver::commit()` to `setUpBeforeClass()` and now it works.

It is strange for me that the exception was thrown only when the filter by group was used. Without a filter, when all tests are run, the exception is not thrown. Do you know what's the relationship?

Thanks for help.

**Comment by mareckigit** [comment]
Finally I resolved this by https://github.com/dmaicher/doctrine-test-bundle/issues/108#issuecomment-621172305

**Comment by dmaicher** [comment]
> It is strange for me that the exception was thrown only when the filter by group was used. Without any filter, when all tests are run, the exception is not thrown. Do you know what's the relationship?

probably its because when you run all tests the test does not run as the first test? But when you run only for that group then the test with `setUpBeforeClass` runs first? That would explain it.
