### ISSUE TITLE
SQLite exceptions are not thrown

### ISSUE THREAD

**Issue by bnymn** [dmaicher/doctrine-test-bundle#138]
Hello,

I am using sqlite for my tests. It seems like unique constraint exception is not thrown. I see that you are using mysql drive on your tests. Do you also support sqlite?

**Comment by dmaicher** [comment]
Yes Sqlite is also supported. Its used on the symfony demo for example with this bundle. 

Also I just ran the tests of this bundle using sqlite - passes without any problems.

So can you be a bit more specific? What exactly does not work?

**Comment by bnymn** [comment]
I am preparing a test case, will inform you soon.

**Comment by bnymn** [comment]
It is working just fine :). Thank you for the awesome work! I think for some reason my migrations are not updated.
