### ISSUE TITLE
StaticDriver now @internal

### ISSUE THREAD

**Issue by kbond** [dmaicher/doctrine-test-bundle#139]
Hey @dmaicher - first of all, I love this bundle, great work!

I see in v6.5.0 you marked the `StaticDriver` as `@internal`. I'm wondering if we could have a discussion about that. A [library](https://github.com/zenstruck/foundry) I maintain has an option to use this bundle and I use the static driver (specifically `isKeepStaticConnections`) to determine if it is enabled and change behaviour based on this. I also use `setKeepStaticConnections` to temporarily "disable" the driver for a certain scenario.

Is there another way I could be handling this? Could we perhaps mark only certain methods as internal? I do see [in the docs](https://github.com/dmaicher/doctrine-test-bundle#debugging), you recommend calling `StaticDriver::commit()` to aid in debugging - this is now an internal call.

**Comment by dmaicher** [comment]
The `StaticDriver` class should not be `@internal` indeed.

I marked the abstract classes to achieve compat with doctrine/dbal v2 and v3 as internal:

https://github.com/dmaicher/doctrine-test-bundle/blob/master/src/DAMA/DoctrineTestBundle/Doctrine/DBAL/AbstractStaticDriver.php#L11

https://github.com/dmaicher/doctrine-test-bundle/blob/master/src/DAMA/DoctrineTestBundle/Doctrine/DBAL/AbstractStaticDriverV3.php#L10

Is that an issue for you?

**Comment by kbond** [comment]
Ok, I suspected that might have been what your intention was. My IDE doesn't flag it as internal but my static analysis tool (psalm) does. I'm happy with this understanding.

Thanks for clarifying!
