### ISSUE TITLE
Allow phpunit 5?

### ISSUE THREAD

**Issue by garak** [dmaicher/doctrine-test-bundle#14]
Hi, since I (finally) moved to php7, I'd like to give a try to the new phpunit.
Currently, I can't upgrade to phpunit `^5.3` because this bundle is requiring phpunit `~4.1`
Do you think that relaxing phpunit requirement to `~4-1|~5.0` would be possible?

**Comment by dmaicher** [comment]
Can you try with a fork if it works with the listener? I'm not familiar with the changes in phpunit 5.

https://github.com/dmaicher/doctrine-test-bundle/blob/master/src/DAMA/DoctrineTestBundle/PHPUnit/PHPUnitStaticDbConnectionListener.php

If yes then I would be happy to allow phpunit 5 :)

**Comment by garak** [comment]
I just tried with success in a project of mine.
Also, it looks like the 5 branch of phpunit just removed a few deprecated (and raised requirements). See https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-5.0.0

**Comment by dmaicher** [comment]
Ok nice. Can you open a PR then? :+1:

**Comment by garak** [comment]
Done.
