### ISSUE TITLE
Working with E2E tests

### ISSUE THREAD

**Issue by JeremyPasco** [dmaicher/doctrine-test-bundle#145]
Hi, I've been trying to use this project for E2E tests (using Panther and/or Selenium) but I seems to have no effect.
I think that makes sense since I have :
- one instance of my app project running (starting it manually)
- a phpunit test suit driving my browser to request the previous instance

So managing transactions from the phpunit process would have no impact on the app process I guess?

I've been trying to start and rollback transactions from the running instance to solve it. To do that I've created 2 endpoints which simply call one of these lines:

```php
// route: e2e/start-transaction
\DAMA\DoctrineTestBundle\Doctrine\DBAL\StaticDriver::beginTransaction();

// route: e2e/rollback-transaction
\DAMA\DoctrineTestBundle\Doctrine\DBAL\StaticDriver::rollback();
```

And now I'm calling these routes from my test suit with requests in setUp and tearDown methods.
I get no error but transactions are still commited.

Any idea of what I'm missing ?
If so I think it would be very interesting to add steps to achieve this goal in the readme. This project seems to fit perfectly with E2E tests!

**Comment by dmaicher** [comment]
Yeah this bundle does not work for e2e tests that go through a webserver. This bundle **only works for tests within the same PHP process** as it keeps DBAL connections as static objects inside the `StaticDriver`.

This is also noted in the Readme for Behat tests:

> Please note that this is only works if the tests are executed in the same process as Behat. This means it cannot work when using e.g. Selenium to call your application.

**Comment by dmaicher** [comment]
I don't see any way of making this work without implementing some connection pool mechanism that would ensure the PHP process spawned via the webserver/php-fpm would re-use existing connections that could be rolled-back then after a test.

**Comment by JeremyPasco** [comment]
Ok thanks a lot for your quick answer!
