### ISSUE TITLE
Error: Active transaction after code changes

### ISSUE THREAD

**Issue by christian-kolb** [dmaicher/doctrine-test-bundle#149]
When running `phpunit` after I did changes in my code I get the following error:

```
$ phpunit src
PHPUnit 8.5.14 by Sebastian Bergmann and contributors.

PDOException {#4862
  #message: "There is already an active transaction"
  #code: 0
  #file: "./vendor/dama/doctrine-test-bundle/src/DAMA/DoctrineTestBundle/Doctrine/DBAL/AbstractStaticDriver.php"
  #line: 70
  +errorInfo: null
  trace: {
    ./vendor/dama/doctrine-test-bundle/src/DAMA/DoctrineTestBundle/Doctrine/DBAL/AbstractStaticDriver.php:70 { …}
    ./vendor/dama/doctrine-test-bundle/src/DAMA/DoctrineTestBundle/PHPUnit/PHPUnitExtension.php:20 { …}
    ./vendor/phpunit/phpunit/src/Runner/Hook/TestListenerAdapter.php:44 { …}
    ./vendor/phpunit/phpunit/src/Framework/TestResult.php:423 { …}
    ./vendor/phpunit/phpunit/src/Framework/TestResult.php:640 { …}
    ./vendor/phpunit/phpunit/src/Framework/TestCase.php:819 { …}
    ./vendor/phpunit/phpunit/src/Framework/TestSuite.php:627 { …}
    ./vendor/phpunit/phpunit/src/Framework/TestSuite.php:627 { …}
    ./vendor/phpunit/phpunit/src/TextUI/TestRunner.php:656 { …}
    ./vendor/phpunit/phpunit/src/TextUI/Command.php:236 { …}
    ./vendor/phpunit/phpunit/src/TextUI/Command.php:195 { …}
    ./vendor/phpunit/phpunit/phpunit:61 { …}
  }
}
```

It fails at:
```php
StaticDriver::beginTransaction();
```

When I run it again it works as usual. Without the bundle I never run into this issue. It's possible that there is something in my code which leads to the problem but I don't really know how I would start debugging it. Did anyone else run into the same issue when using this bundle?

Any ideas how to debug it?

**Comment by dmaicher** [comment]
Can you debug the exact queries being executed on the connection during this test? Should be possible to get the Doctrine DBAL logs somehow

**Comment by christian-kolb** [comment]
> Can you debug the exact queries being executed on the connection during this test? Should be possible to get the Doctrine DBAL logs somehow

@dmaicher Good idea, I will test it within the next days and update this issue.

**Comment by dmaicher** [comment]
Closing for now. Let me know if this is still an issue and you have some more input on this.

**Comment by christian-kolb** [comment]
Sorry, I haven't been able to work on it. But I will reply as soon as I'm able to.
