### ISSUE TITLE
Better detection of doctrine/dbal installed version

### ISSUE THREAD

**Issue by dFayet** [dmaicher/doctrine-test-bundle#153]
In the [StaticDriver](https://github.com/dmaicher/doctrine-test-bundle/blob/8c8eac0271e533551ee5bffc9d04d192dad19fe3/src/DAMA/DoctrineTestBundle/Doctrine/DBAL/StaticDriver.php) the detection of the doctrine/dbal version is based only on the existence of an interface,

This is not a 100% exact science as class aliases could break this detection.

Even if we can arguably say this is the problem of the code creating the alias, like in https://github.com/getsentry/sentry-symfony/issues/484

**Comment by dmaicher** [comment]
Indeed I would also argue that this is an issue of `getsentry/sentry-symfony` :confused: 

Any idea how we could make it more robust?
