### ISSUE TITLE
Incompatible with DoctrineBundle 2.4 + ORM 2.9

### ISSUE THREAD

**Issue by mbabker** [dmaicher/doctrine-test-bundle#158]
DoctrineBundle 2.4 will drop support for ORM versions before 2.9.  As of DoctrineBundle 2.4, it is only configuring the metadata cache using the PSR-6 typehinted `Doctrine\ORM\Configuration::setMetadataCache()` method.  Since the `DAMA\DoctrineTestBundle\Doctrine\Cache\StaticArrayCache` class doesn't implement the PSR, this causes things to fail over pretty hard.  With Doctrine's cache library [being deprecated](https://github.com/doctrine/cache/issues/354), it would also probably be good to replace the cache implementation used here.

For now, this can be worked around by setting the `enable_static_meta_data_cache` and `enable_static_query_cache` options to false.

**Comment by dmaicher** [comment]
Indeed. Thanks for reporting this.

I will look into this asap.

**Comment by dmaicher** [comment]
@mbabker would you be able to test https://github.com/dmaicher/doctrine-test-bundle/pull/161 ?

**Comment by mbabker** [comment]
With that PR everything's working fine for me with the caches re-enabled.

**Comment by calvera** [comment]
hello, any info when it will be released? thanks

**Comment by dmaicher** [comment]
Released now: https://github.com/dmaicher/doctrine-test-bundle/releases/tag/v6.6.0
