### ISSUE TITLE
Error with latest versions of doctrine

### ISSUE THREAD

**Issue by garak** [dmaicher/doctrine-test-bundle#160]
Using doctrine/orm 2.9 and doctrine/doctrine-bundle 2.4-dev, when I try to update schema via command, I get the following error (in Configuration.php line 336):

>Doctrine\ORM\Configuration::setMetadataCache(): Argument #1 ($cache) must be of type Psr\Cache\CacheItemPoolInterface, DAMA\DoctrineTestBundle\Doctrine\Cache\StaticArrayCache given, cal  
  led in /myproject/var/cache/test/ContainerBwanHN2/Infrastructure_KernelTestDebugContainer.php on line 7468

Probably related to https://github.com/doctrine/DoctrineBundle/issues/1351

**Comment by dmaicher** [comment]
See https://github.com/dmaicher/doctrine-test-bundle/issues/158
