### ISSUE TITLE
Doctrine\DBAL\Driver\ExceptionConverterDriver is deprecated

### ISSUE THREAD

**Issue by ettoredn** [dmaicher/doctrine-test-bundle#163]
1x: The "DAMA\DoctrineTestBundle\Doctrine\DBAL\AbstractStaticDriverV2" class implements "Doctrine\DBAL\Driver\ExceptionConverterDriver" that is deprecated.
    1x in PHPUnitExtension::executeBeforeFirstTest from DAMA\DoctrineTestBundle\PHPUnit

**Comment by dmaicher** [comment]
https://github.com/dmaicher/doctrine-test-bundle/issues/129
