### ISSUE TITLE
Allow PHPUnit 6?

### ISSUE THREAD

**Issue by garak** [dmaicher/doctrine-test-bundle#17]
PHPUnit 6.0 will be out in less than 2 months (see [milestones](https://github.com/sebastianbergmann/phpunit/milestones)), but this bundle is still not allowing it.
Is there anything specific change in PHPUnit 6.0 that is preventing raising requirements to `"~4.1|~5.0|~6.0"`?
I took a rapid look to [changelog](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md) and there don't seem to be any.

**Comment by dmaicher** [comment]
Good point :+1:  Have not tested it with version 6.0 yet but looking at the changelog it should work indeed :blush: 

Do you have any project you could test it on?

**Comment by garak** [comment]
I do. I propose to allow PHPUnit 6 in master, then if OK you could release a new tag.
Another acceptable option would be to keep it in master only, until PHPUnit 6 stable will be out.

**Comment by dmaicher** [comment]
Agreed :wink: It's on master now. Let me know if everything works as it should :blush: 
I use this bundle currently on PHP 5.6 projects only so I cannot test it properly :stuck_out_tongue_closed_eyes:

**Comment by garak** [comment]
Just tried, it's fine :+1:

**Comment by dmaicher** [comment]
Perfect :+1: Then I can create a new release already :blush:
