### ISSUE TITLE
StaticArrayCache return type breaks tests

### ISSUE THREAD

**Issue by williarin** [dmaicher/doctrine-test-bundle#174]
https://github.com/dmaicher/doctrine-test-bundle/blob/919a91b85629c28baab7e20faae553ad43799ba7/src/DAMA/DoctrineTestBundle/Doctrine/Cache/StaticArrayCache.php#L14

This newly added return type breaks the tests.

```php
/*
 * @return mixed|false The cached data or FALSE, if no cache entry exists for the given id.
 */
```

**Comment by dmaicher** [comment]
Indeed :man_facepalming: Thanks for reporting. Fixed in https://github.com/dmaicher/doctrine-test-bundle/pull/175
