### ISSUE TITLE
PHPUnit\Framework\TestListener that is deprecated

### ISSUE THREAD

**Issue by pouya-amani-cxt** [dmaicher/doctrine-test-bundle#185]
I upgraded did upgrade on PHP -> 8.0 and packages as well. and got these errors:

`The "DAMA\DoctrineTestBundle\PHPUnit\PHPUnitListener" class implements "PHPUnit\Framework\TestListener" that is deprecated Use the `TestHook` interfaces instead.`

`The "DAMA\DoctrineTestBundle\PHPUnit\PHPUnitListener" class uses "PHPUnit\Framework\TestListenerDefaultImplementation" that is deprecated The `TestListener` interface is deprecated.`

Seems just need to replace some class names.

Would you please check and give advice.

**Comment by dmaicher** [comment]
Which version of PHPUnit are you using? Please check the readme. You probably just need to use the extension instead of the listener.

**Comment by pouya-amani-cxt** [comment]
I am using: PHP 8.0.12 (cli) (built: Oct 21 2021 15:52:54) ( NTS )
