### ISSUE TITLE
Support Symfony 6

### ISSUE THREAD

**Issue by vertx-one** [dmaicher/doctrine-test-bundle#204]
I tried to upgrade from symfony 5.4 to symfony 6, on step [https://symfony.com/doc/current/setup/upgrade_major.html#deprecations-in-phpunit](https://symfony.com/doc/current/setup/upgrade_major.html#deprecations-in-phpunit) I got notice
```
The "DAMA\DoctrineTestBundle\Doctrine\DBAL\AbstractStaticDriver" class implements "Doctrine\DBAL\VersionAwarePlatformDriver" that is deprecated All drivers will have to be aware of the server version in the next major release.
```

**Comment by dmaicher** [comment]
See https://github.com/dmaicher/doctrine-test-bundle/issues/188
