### ISSUE TITLE
Remove deprecated interface ExceptionConverterDriver 

### ISSUE THREAD

**Issue by NafaaAzaiez** [dmaicher/doctrine-test-bundle#207]
Deprecation details:

`
The "DAMA\DoctrineTestBundle\Doctrine\DBAL\AbstractStaticDriverV2" class implements "Doctrine\DBAL\Driver\ExceptionConverterDriver" that is deprecated.
`

**Comment by dmaicher** [comment]
https://github.com/dmaicher/doctrine-test-bundle/issues/129
