### ISSUE TITLE
There is no active transaction

### ISSUE THREAD

**Issue by yanarowana123** [dmaicher/doctrine-test-bundle#216]
"There is no active transaction" occurs when trying to flush $manager->flush(). 

package version [v7.1.1](https://github.com/dmaicher/doctrine-test-bundle/releases/tag/v7.1.1)

doctrine/dbal - 3.3.6

**Comment by yanarowana123** [comment]
Found out that problems occurs only when i use doctrine-data-fixtures. 

I guess the problem refers to https://www.doctrine-project.org/projects/doctrine-data-fixtures/en/latest/explanation/transactions-and-purging.html. 

I am using Mysql 5.7

**Comment by dmaicher** [comment]
Yeah. Can you try configuring it to use `DELETE` instead of `TRUNCATE`?

**Comment by yanarowana123** [comment]
It works now. Thanks!

**Comment by beejaz** [comment]
> Yeah. Can you try configuring it to use `DELETE` instead of `TRUNCATE`?

Hi, can someone point me in correct dirrection for where I need to change "it" to `DELETE` instead of `TRUNCATE`?

Im using php 8.2, MySQL 8, Symfony 6.3, dama/doctrine-test-bundle 7.2 and doctrine/doctrine-fixtures-bundle 3.4 and I get this error when adding this bundle in phpunit.xml.dist
