### ISSUE TITLE
Does this work with Symfony Panther?

### ISSUE THREAD

**Issue by arderyp** [dmaicher/doctrine-test-bundle#218]
https://github.com/symfony/panther

My guess is no, because panther spins up it's owl webdriven client that executes action that doctrine-test-bundle probably doesn't have access to see and roll back.  If there was any way to achieve this, however, that would be amazing.

**Comment by dmaicher** [comment]
Indeed this does not work. We need a single php process to roll-back the DB changes.

**Comment by arderyp** [comment]
That's what a thought, thanks for the quick response!  The webdriven client's are both a blessing and a curse.
