### ISSUE TITLE
allow config to live at config/packages instead of config/packages/test

### ISSUE THREAD

**Issue by arderyp** [dmaicher/doctrine-test-bundle#219]
I tried to move the config file and manually update `symfony.lock` to point to the proper path, but it went belly up.

as of Symfony 5.4 and 6, the new config standard seems to have replaced the `dev/` `test/` `prod/` sub-directories with more convenient `when@dev` `when@test` `when@prod` properties in a singular config file.

**Comment by dmaicher** [comment]
This should work just fine. See https://github.com/symfony/demo/blob/main/config/packages/dama_doctrine_test_bundle.yaml

**Comment by arderyp** [comment]
I'm an idiot, I forgot the `when@test`!  Thank you for the quick response :)
