### ISSUE TITLE
Deprecated VersionAwarePlatformStaticDriver class implements  VersionAwarePlatformStaticDriver 

### ISSUE THREAD

**Issue by fransweerts** [dmaicher/doctrine-test-bundle#235]
Hello,

I have found this deprecated message in my log:

Deprecated: The "DAMA\DoctrineTestBundle\Doctrine\DBAL\VersionAwarePlatformStaticDriver" class implements "Doctrine\DBAL\VersionAwarePlatformDriver" that is deprecated All drivers will have to be aware of the server version in the next major release.

I am using  "doctrine/dbal version 3.5.1" and  "dama/doctrine-test-bundle 7.1.1".

**Comment by dmaicher** [comment]
Yeah I'm aware of it. I don't think there is any way to fix this deprecation. Its similar to https://github.com/dmaicher/doctrine-test-bundle/issues/129

**Comment by fransweerts** [comment]
Thank you for the quick response.

 https://github.com/dmaicher/doctrine-test-bundle/issues/129#issuecomment-864889080_

The current version of dama/doctrine-test-bundle is only supporting DBAL 3. 
If I'm understanding it correctly, its possible to safely remove the "implement VersionAwarePlatformDriver" because you are not supporting DBAL 2 anymore?

**Comment by dmaicher** [comment]
> because you are not supporting DBAL 2 anymore?

? This is deprecated in DBAL 3 and removed in DBAL 4.

See https://github.com/doctrine/dbal/blob/3.5.x/src/Connection.php#L404

We cannot just remove `implements VersionAwarePlatformDriver`. This would change behavior.
