### ISSUE TITLE
The "DAMA\DoctrineTestBundle\Doctrine\DBAL\VersionAwarePlatformStaticDriver" class implements deprecated "Doctrine\DBAL\VersionAwarePlatformDriver"

### ISSUE THREAD

**Issue by steffenbrand** [dmaicher/doctrine-test-bundle#240]
I get the following deprecation info:

`User Deprecated: The "DAMA\DoctrineTestBundle\Doctrine\DBAL\VersionAwarePlatformStaticDriver" class implements "Doctrine\DBAL\VersionAwarePlatformDriver" that is deprecated All drivers will have to be aware of the server version in the next major release.`

https://github.com/doctrine/dbal/blob/3.5.x/UPGRADE.md#deprecated-driver-level-apis-that-dont-take-the-server-version-into-account

doctrine/dbal: 3.5.2
dama/doctrine-test-bundle: 7.1.1

I think the change is in the `Middleware.php`, where now always a `StaticDriver` should be returned :man_shrugging:  

Is there a way for me to mitigate this?  
Like setting some configuration so my own `Middleware.php` is used or something like this?

**Comment by dmaicher** [comment]
There is no way to fix this unfortunately. See https://github.com/dmaicher/doctrine-test-bundle/issues/235
