### ISSUE TITLE
PHPUnit 10

### ISSUE THREAD

**Issue by ruudk** [dmaicher/doctrine-test-bundle#242]
Does this also work with [PHPUnit 10](https://github.com/sebastianbergmann/phpunit/releases/tag/10.0.0)?

The XSD says this is no longer valid:
<img width="745" alt="Screenshot 2023-02-03 at 20 01 42@2x" src="https://user-images.githubusercontent.com/104180/216685596-a20d1909-2048-44ec-bb1f-0f1e6cbafaf6.png">

- https://github.com/sebastianbergmann/phpunit/blob/main/ChangeLog-10.0.md

**Comment by dmaicher** [comment]
As of now its not working with version 10. I'm looking into it

**Comment by dmaicher** [comment]
@ruudk could you try https://github.com/dmaicher/doctrine-test-bundle/pull/243 ? 

I don't have a project yet using PHPUnit 10 but the testsuite for this bundle passes which hopefully means it works fine :blush: 

Has to be configured like this for v10:

```xml
    <extensions>
        <bootstrap class="DAMA\DoctrineTestBundle\PHPUnit\PHPUnitExtension" />
    </extensions>
```

**Comment by garak** [comment]
I tried it on a project of mine and it seems working.
I can't tell for sure because I have had many failures, but I guess it's something related to Symfony itself

**Comment by fico7489** [comment]
@dmaicher  it works! thanks!
