### ISSUE TITLE
DBAL Deprecation: VersionAwarePlatformDriver

### ISSUE THREAD

**Issue by Chris53897** [dmaicher/doctrine-test-bundle#250]
The "DAMA\DoctrineTestBundle\Doctrine\DBAL\VersionAwarePlatformStaticDriver" class implements "Doctrine\DBAL\VersionAwarePlatformDriver" that is deprecated All drivers will have to be aware of the server version in the next major release.

I noticed the PR for DBAL 4 support, so maybe you are still aware of this deprecation.
CI-Logs are not visible anymore for the PR.

**Comment by dmaicher** [comment]
see https://github.com/dmaicher/doctrine-test-bundle/issues/235

this is fixed in the 8.0 beta release
