### ISSUE TITLE
v8 breaks behat integration

### ISSUE THREAD

**Issue by aszenz** [dmaicher/doctrine-test-bundle#270]
I get the error `An open transaction is needed` when doing `flush()` inside Feature Context file.
Downgrading to v7 fixes the issue, as does wrapping the code in `wrapInTransaction`

**Comment by aszenz** [comment]
Reason we get an error on the flush is because we are doing `LockMode::PESSIMISTIC_WRITE` on one of our finds, this operation requires an active transaction.

I'll try to isolate why the transaction is not started on v8

**Comment by dmaicher** [comment]
Closing for now. Let me know if there are any updates.
