### ISSUE TITLE
This bundle relies on savepoints for nested database transactions. You need to enable "use_savepoints" on the Do   ctrine DBAL config for connection "default".

### ISSUE THREAD

**Issue by abdounikarim** [dmaicher/doctrine-test-bundle#275]
Hello, I have this error message on the 8.0.1 version of the bundle when trying to drop database.
No error with the 7.3 version.

With Symfony 6.4 fresh application without custom doctrine configuration.

**Comment by dmaicher** [comment]
You need to enable savepoints. See https://github.com/dmaicher/doctrine-test-bundle/issues/274

I will add a comment for this in readme to make it more clear.
