### ISSUE TITLE
[Suggestion]Reset auto-increment

### ISSUE THREAD

**Issue by Rewieer** [dmaicher/doctrine-test-bundle#29]
I'm not a connaisseur of Doctrine, but I've seen that rolling back doesn't reinitialize the auto-increment fields. So every test just increases the ID until it boom.
Maybe there's a way to scan the tables with auto-increment fields and reinitialize them ?

**Comment by dmaicher** [comment]
Indeed currently the auto-increment ID's will keep increasing with every test that does insertions. 

But this should not be a problem as the schema will most likely be rebuild before running the test-suite anyway :wink: 

So what exactly do you mean with `... until it boom.`?

Seems quite tricky and error prone to do this automatically to be honest.

**Comment by Rewieer** [comment]
I'm kind of convinced by the fact that the database should be rebuilt before launching the test so, I guess i'm ok with it.
Until it boom, it's kind of abusive i know.. i'm talking about the moment when the ID will increase to it's limit. Not happening quite often :D
