### ISSUE TITLE
How to detect dama wrapper is active ?

### ISSUE THREAD

**Issue by Kytrix** [dmaicher/doctrine-test-bundle#295]
Hello,
I previously used a test inside my ancestor test class constructor:
  if(!$this->em->getConnection()->isTransactionActive())
            $this->fail("No active transaction ! you could lost data  !\n");
 
But it seems to not work with lasts versions.

I made another test by looking in Connection params.

I try to get the driver class, but because the wrapperDriver is private I'm not able to test it's class, despite my debugger is able to see it :
![image](https://github.com/dmaicher/doctrine-test-bundle/assets/3098540/39dcda0d-1a5f-4808-8ed6-5c4fbb2320c4)

Is there a better solution ?

**Comment by dmaicher** [comment]
Out of curiosity: why would you need to detect if the bundle is managing a connection? :thinking:

**Comment by Kytrix** [comment]
Because I already have the issue of the tests were running without transaction (the bundle was somehow been disabled) and I don't want this could append again.

**Comment by dmaicher** [comment]
You could try

```php
/** @var \PDO $connection */
$connection = $this->em->getConnection()->getNativeConnection();
if(!$connection->inTransaction()) {
    $this->fail("No active transaction ! you could lost data !\n");
}

**Comment by Kytrix** [comment]
Thank you very much ! it works !
