### ISSUE TITLE
Bug:  Rollback doesn't work if `StaticDriver::isKeepStaticConnections()` return false

### ISSUE THREAD

**Issue by maidmaid** [dmaicher/doctrine-test-bundle#308]
When the driver rollbacks, it iterates on `self::$connections`:
https://github.com/dmaicher/doctrine-test-bundle/blob/1f81a280ea63f049d24e9c8ce00e557b18e0ff2f/src/DAMA/DoctrineTestBundle/Doctrine/DBAL/StaticDriver.php#L64-L69

But when if `self::isKeepStaticConnections()` return false, `self::$connections` is never set:
https://github.com/dmaicher/doctrine-test-bundle/blob/1f81a280ea63f049d24e9c8ce00e557b18e0ff2f/src/DAMA/DoctrineTestBundle/Doctrine/DBAL/StaticDriver.php#L22-L26

Should it be populated like below ?
https://github.com/dmaicher/doctrine-test-bundle/blob/1f81a280ea63f049d24e9c8ce00e557b18e0ff2f/src/DAMA/DoctrineTestBundle/Doctrine/DBAL/StaticDriver.php#L31-L34

**Comment by maidmaid** [comment]
As a workaround, I use the next line in my tests:

```php
StaticDriver::setKeepStaticConnections(false);
```

**Comment by dmaicher** [comment]
Hm normally this is set to true in the beginning of the test suite via

https://github.com/dmaicher/doctrine-test-bundle/blob/1f81a280ea63f049d24e9c8ce00e557b18e0ff2f/src/DAMA/DoctrineTestBundle/PHPUnit/PHPUnitExtension.php#L50

https://github.com/dmaicher/doctrine-test-bundle/blob/1f81a280ea63f049d24e9c8ce00e557b18e0ff2f/src/DAMA/DoctrineTestBundle/PHPUnit/PHPUnitExtension.php#L102

Are you running tests with PHPUnit process isolation? Then this bundle will not work properly.

**Comment by maidmaid** [comment]
If we use the db in a data provider, it looks like this problem occurs.

**Comment by dmaicher** [comment]
> If we use the db in a data provider, it looks like this problem occurs.

yes this is by design unfortunately. Data provider code is executed before all other tests and there is no rollback logic.

I guess you need to work around that by moving the db access code into the test code or manually fiddle around with `StaticDriver::setKeepStaticConnections(true)` and rolling back if needed.

**Comment by maidmaid** [comment]
This workaround works fine:

```php
#[DataProvider('provide')]
public function test($entity): void
{
    // ... (do write operations in db)
}

public static function provide(): iterable
{
    self::bootKernel();
    StaticDriver::setKeepStaticConnections(true);

    // ... (get data from db)
    yield [$entity1];
    yield [$entity2];

    StaticDriver::Rollback();
}
```

**Comment by maidmaid** [comment]
It could be possible to directly handle it thanks to these PHPUnit subscribers I guess:

- DataProviderMethodCalledSubscriber
- DataProviderMethodFinishedSubscriber

**Comment by maidmaid** [comment]
Easier workaround (recalling `bootKernel()` inside the test):

```php
#[DataProvider('provide')]
public function test($entity): void
{
    self::bootKernel();
    // ... (do write operations in db)
}

public static function provide(): iterable
{
    self::bootKernel();

    // ... (get data from db)
    yield [$entity1];
    yield [$entity2];
}
```
