### ISSUE TITLE
Conflict with Symfony PHPUnit Bridge

### ISSUE THREAD

**Issue by bocharsky-bw** [dmaicher/doctrine-test-bundle#31]
Currently, this bundle has a conflict with Symfony PHPUnit Bridge one which provides `./vendor/bin/simple-phpunit` script, see https://github.com/symfony/symfony/issues/23598

The only solution I see is to move `phpunit/phpunit` dependency to `require-dev` section and add one more step to the installation to ask devs manually install PHPUnit.

**Comment by dmaicher** [comment]
Thanks for the report :wink: This is indeed a problem :cry: I will look into it later today.

**Comment by bocharsky-bw** [comment]
Thanks for the quick reply! I'd really love to see a better solution for this case :/

**Comment by dmaicher** [comment]
@bocharsky-bw can you confirm that it works for you when doing this?

1. require dev branch: `"dama/doctrine-test-bundle": "dev-phpunit-dev as 1.1",`
2. change phpunit listener to: `<listener class="\DAMA\DoctrineTestBundle\PHPUnit\LegacyPHPUnitListener" />`

**Comment by bocharsky-bw** [comment]
Hm, does not work, still have:
> Error: Call to undefined method PHPUnit_Framework_TestResult::warnings() in /Users/victor/www/sites/symfony-demo/vendor/symfony/phpunit-bridge/bin/.phpunit/phpunit-5.7/src/TextUI/ResultPrinter.php on line 293

Actually, I test it on Symfony Demo project.

**Comment by dmaicher** [comment]
Did you also run `composer update` to remove the root `phpunit/phpunit` dependency?

**Comment by bocharsky-bw** [comment]
Oops, forgot! Yea, the problem is gone 👍

**Comment by dmaicher** [comment]
Cool :+1: 

Ok then I will prepare a new release `3.0.0` which can be used for phpunit <6 and 6+ then :blush: Actually simplifies things and no need to maintain two versions `1.x` and `2.x` anymore.

**Comment by bocharsky-bw** [comment]
Thanks for the quick fix, David!

**Comment by dmaicher** [comment]
You can require `^3.0` now and use the new release :+1: 

Thanks again for reporting the problem.
