### ISSUE TITLE
Not compatible with PHPUnit v6

### ISSUE THREAD

**Issue by Soullivaneuh** [dmaicher/doctrine-test-bundle#41]
Because of the namespace changes:

```
Fatal error: Class 'PHPUnit_Framework_BaseTestListener' not found in /code/vendor/dama/doctrine-test-bundle/src/DAMA/DoctrineTestBundle/PHPUnit/LegacyPHPUnitListener.php on line 7
```

**Comment by Soullivaneuh** [comment]
Well, next time I'll read the README.

Sorry for that.

**Comment by dmaicher** [comment]
No problem :wink: 

Soon 4.0.0 will be released and then those problems are gone as the same listener can be used for both PHPUnit 5 and 6+

**Comment by Soullivaneuh** [comment]
Great!

Thanks for your bundle BTW, it help a lot! I may write a blog post about it when I'll have time. :wink:

**Comment by dmaicher** [comment]
Thanks. Great to hear that :+1:
