### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by ThePixelDeveloper** [dmaicher/doctrine-test-bundle#47]
I've tried this bundle on a project of mine and haven't seen much of a performance increase over using the ORMPurger and loading fixtures with Doctrine for each test case. Is there a benchmark where I can see a before and after for this bundle?

It doesn't bother me too much as the bundle has other advantages, but I wonder if I'm missing out on a speed increase to something I'm not doing correctly.

Cheers, thanks for the hard work.

**Comment by dmaicher** [comment]
I unfortunately don't have any benchmarks anymore for the transactional feature vs purging and re-inserting fixtures. I just remember that for me this way was quite a bit more performant.

The biggest performance impact achieves this bundle through optimized doctrine caches.

On my biggest symfony testsuite (with tons of functional tests):

`kernel.debug=true`:

No caching features of this bundle active:

```
...................                                           2276 / 2276 (100%)

Time: 33.72 minutes, Memory: 5152.01MB
```

With caching enabled (`enable_static_meta_data_cache: true`, `enable_static_query_cache: true`):

```
............................................................. 2257 / 2276 ( 99%)
...................                                           2276 / 2276 (100%)

Time: 10.33 minutes, Memory: 2934.01MB
```

And here with `kernel.debug=false`:

```
............................................................. 2257 / 2276 ( 99%)
...................                                           2276 / 2276 (100%)

Time: 27.48 minutes, Memory: 5034.01MB
```



With caching:
```
............................................................. 2257 / 2276 ( 99%)
...................                                           2276 / 2276 (100%)

Time: 4.47 minutes, Memory: 1558.01MB
```

@ThePixelDeveloper you have the caching options enabled?

**Comment by ThePixelDeveloper** [comment]
@dmaicher I had another look at our workflow and noticed we were missing something ... 

``` bash
APP_DEBUG=0 ./vendor/bin/phpunit
```

vs 

``` bash
./vendor/bin/phpunit
```

made a significant difference the duration of the test suite. It might be worth mentioning in the README.

**Comment by dmaicher** [comment]
Yes good idea :+1: Maybe will add some info on how to run the tests even faster in the readme
