### ISSUE TITLE
[Question] Problem with symfony's PhpUnit Bridge

### ISSUE THREAD

**Issue by nikophil** [dmaicher/doctrine-test-bundle#61]
Hello,

i'd like to use your bundle with php 7.1 and symfony 4.1
But i'm running into this error :
```
PHP Fatal error:  Declaration of DAMA\DoctrineTestBundle\PHPUnit\PHPUnitListener::startTestSuite(PHPUnit\Framework\TestSuite $suite) must be compatible with PHPUnit_Framework_TestListener::startTestSuite(PHPUnit_Framework_TestSuite $suite) in /home/niko/works/fiducial/bizportal/vendor/dama/doctrine-test-bundle/src/DAMA/DoctrineTestBundle/PHPUnit/PHPUnitListener.php on line 9
```

i'm using the phpunit bridge, and the php unit version that naturally comes with it : it's actually the 5.7
I can't find a way to tell PhpUnit Bridge to use a more recent version...
i saw this issue : #31 but i can't find a way to solve my problem

thanks for your help

**Comment by dmaicher** [comment]
I can have a look later today. But it seems weird that the phpunit bridge requires a non-maintained phpunit version?

Indeed the listener that ships with this bundle is only compatible with phpunit 6+.

**Comment by dmaicher** [comment]
It seems you can define an environment variable for the version to use?

See this fix I did for the symfony demo (which also uses the phpunit bridge):

https://github.com/symfony/demo/commit/f1f53a69989491cd65bf9fcbe82f75e5f53d0ded

**Comment by nikophil** [comment]
Hello,

thank you for this really quick and relevant answer :)
i had to add this var env to my phpunit.xml file and it did the work !
Shouldn't you add it to the docs ?

i agree it's strange that the PhpUnitBridge ships this really old
version.... but i've juste made a test from a fresh new install of the
symfony skeleton, and this is actually the true


2018-06-07 11:45 GMT+02:00 David Maicher <notifications@github.com>:

**Comment by nikophil** [comment]
and by the way, thanks for this bundle, it's working great !

**Comment by nikophil** [comment]
perfect !

**Comment by siewert87** [comment]
Hey,
anyone checked this? https://github.com/symfony/demo/issues/811
Best,
Christian
