### ISSUE TITLE
Integrate these features directly in doctrine/doctrine-bundle ?

### ISSUE THREAD

**Issue by B-Galati** [dmaicher/doctrine-test-bundle#63]
Hello,

Everything is in the title.

What do you think?

**Comment by dmaicher** [comment]
Well it would be doable I guess :blush: 

The question is if there is any real benefit in doing so?

**Comment by B-Galati** [comment]
Yes, IMO they are "must have opt-in features" that one should have out of the box.
These features would benefit from the Symfony eco-system by being merged into doctrine bundle.

**Comment by dunglas** [comment]
Hi there,

I want to add an easy way to deal with fixtures Symfony Panther. Actually, thank to your bundle, there is almost nothing to do!

However, it's difficult for developers to discover the required packages (Doctrine Fixtures + this one + @theofidry's AliceDataFixtures + maybe hautelook/AliceBundle).

It's a lot, and most of these packages don't have an official recipes yet. Reducing the number of packages would improve the DX and the discoverability (as well as the maintenance).

**Comment by dmaicher** [comment]
> However, it's difficult for developers to discover the required packages (Doctrine Fixtures + this one + @theofidry's AliceDataFixtures + maybe hautelook/AliceBundle).

With this point I agree although since a while this bundle is mentioned in the docs: https://symfony.com/doc/current/testing/database.html

**Comment by dmaicher** [comment]
I'm closing this for now
