### ISSUE TITLE
PhpUnit process isolation

### ISSUE THREAD

**Issue by matiux** [dmaicher/doctrine-test-bundle#67]
I'm working on sf 4.1.7 with phpunit 7.4.
If I run tests with `process isolation = true`, tests are not transactional :confused:
Instead with `process isolation = false` all works well

**Comment by dmaicher** [comment]
This is a duplicate of https://github.com/dmaicher/doctrine-test-bundle/issues/66, right? I'm on vacation currently but feel free to give it a try yourself and contribute the fix :)

**Comment by dmaicher** [comment]
Duplicate of https://github.com/dmaicher/doctrine-test-bundle/issues/66
