### ISSUE TITLE
Problem with unique validator

### ISSUE THREAD

**Issue by garak** [dmaicher/doctrine-test-bundle#7]
Not sure if this is a real issue, or it's just me not understanding correctly.
I'm testing that a UniqueEntity constraint is correctly applied (on a "create" form for FosUserBundle I'm testing that I cannot create an user with the same email as an existing user).
With this bundle enabled, it looks like constraint is not triggered, resulting in an Exception at database level.
If if set `enable_static_connection: false` in configuration, the constraint is working again, but it looks like I lose the "rollback" feature

**Comment by dmaicher** [comment]
Thx for the report. Hmm that sounds weird indeed. 

When do you create the fixtures? Once before the whole testsuite runs?

Can I see the test that fails?

**Comment by garak** [comment]
I load fixtures once, before running test suite.
Here is the test:
```php
    public function testNewErrorForDuplicateEmail()
    {
        $client = static::createClient();
        $crawler = $client->request('GET', '/admin/users');
        $crawler = $client->click($crawler->selectLink('add new')->link());
        $form = $crawler->filter('form[name="user"] *[type="submit"]')->form([
            'user[email]' => 'berto@example.org',  // this email already exists in fixtures
            'user[username]' => 'berto',
            'user[password]' => 'qwerty',
        ]);
        $crawler = $client->submit($form);
        // here the test fails with DBALException duplicate key
        $this->assertTrue($client->getResponse()->isOk());
        $this->assertCount(1, $crawler->filter('div.alert-danger:contains("already")'));
    }
```

**Comment by garak** [comment]
OK.
Sorry, it's my fault. Indeed, there is no UniqurEntity constraint involved, since I'm using a DTO and validating on that instead of FosUSer entity.
I'm closing this.
