### ISSUE TITLE
Class "\DAMA\DoctrineTestBundle\PHPUnit\PHPUnitListener" does not implement the PHPUnit_Framework_TestListener interface

### ISSUE THREAD

**Issue by metaer** [dmaicher/doctrine-test-bundle#76]
When I use command
`./vendor/bin/simple-phpunit`
from this documentation: https://symfony.com/doc/3.4/testing

I get
  _- Installing phpunit/phpunit (5.7.27): Downloading (100%)_
_...
Writing lock file
Generating optimized autoload files_

and then such error:

_Class "\DAMA\DoctrineTestBundle\PHPUnit\PHPUnitListener" does not implement the PHPUnit_Framework_TestListener interface_

**Comment by dmaicher** [comment]
See this part of the readme:

> Make sure you also have phpunit/phpunit available as a dev dependency (versions 6, 7 and 8 are supported with the built in listener) to run your tests. Alternatively this bundle is also compatible with symfony/phpunit-bridge and its simple-phpunit script. (Note: you may need to make sure the phpunit-bridge requires the correct PHPUnit 6+ Version using the environment variable SYMFONY_PHPUNIT_VERSION).

PHPUnit 5 is not supported anymore.
