### ISSUE TITLE
Deprecations notices with phpunit 8

### ISSUE THREAD

**Issue by B-Galati** [dmaicher/doctrine-test-bundle#77]
Hello!

I am having these deprecations notices from phpunit thanks to SymfonyTestListener.

```
  1x: The "DAMA\DoctrineTestBundle\PHPUnit\PHPUnitListener" class implements "PHPUnit\Framework\TestListener" that is deprecated Use the `TestHook` interfaces instead.
    1x in DebugClassLoader::loadClass from Symfony\Component\Debug

  1x: The "PHPUnit\Framework\TestListener" interface is considered internal This class is not covered by the backward compatibility promise for PHPUnit. It may change without further notice. You should not use it from "DAMA\DoctrineTestBundle\PHPUnit\PHPUnitListener".
    1x in DebugClassLoader::loadClass from Symfony\Component\Debug
```

I did a custom extension to remove these:

```
<?php

namespace App\Tests\Func;

use DAMA\DoctrineTestBundle\Doctrine\DBAL\StaticDriver;
use PHPUnit\Runner\AfterLastTestHook;
use PHPUnit\Runner\AfterTestHook;
use PHPUnit\Runner\BeforeFirstTestHook;
use PHPUnit\Runner\BeforeTestHook;

class TransactionPhpUnitExtension implements BeforeFirstTestHook, AfterLastTestHook, BeforeTestHook, AfterTestHook
{
    public function executeBeforeFirstTest(): void
    {
        StaticDriver::setKeepStaticConnections(true);
    }

    public function executeBeforeTest(string $test): void
    {
        StaticDriver::beginTransaction();
    }

    public function executeAfterTest(string $test, float $time): void
    {
        StaticDriver::rollBack();
    }

    public function executeAfterLastTest(): void
    {
        StaticDriver::setKeepStaticConnections(false);
    }
}
```

What do you think?

**Comment by B-Galati** [comment]
I could try to make a PR if providing an Extension for Phpunit8 looks ok to you.

**Comment by dmaicher** [comment]
Yes any PR to fix this is welcome!

I guess we need another condition like this one?

https://github.com/dmaicher/doctrine-test-bundle/blob/master/src/DAMA/DoctrineTestBundle/PHPUnit/PHPUnitListener.php#L26

wondering why the travis build did not show me any deprecations :cry:

**Comment by B-Galati** [comment]
> I guess we need another condition like this one?
> 
> https://github.com/dmaicher/doctrine-test-bundle/blob/master/src/DAMA/DoctrineTestBundle/PHPUnit/PHPUnitListener.php#L26

No because it's an extension and it is not configured the same way. I think a new class and a proper documentation update will do the job just fine. WDYT?

> wondering why the travis build did not show me any deprecations cry

I guess, they showed up for me because I have Symfony Test Listener activated on phpunit config.
Don't know what would be the normal behavior without it.

**Comment by B-Galati** [comment]
I'll make a PR then!

**Comment by dmaicher** [comment]
> I guess, they showed up for me because I have Symfony Test Listener activated on phpunit config.
Don't know what would be the normal behavior without it.

actually the listener is also active for the tests of this bundle :blush: 

https://github.com/dmaicher/doctrine-test-bundle/blob/master/tests/phpunit.xml#L35

**Comment by B-Galati** [comment]
Indeed! Weird!
