### ISSUE TITLE
Catching exception is not working

### ISSUE THREAD

**Issue by garak** [dmaicher/doctrine-test-bundle#8]
There is my scenario: using a DTO for a FosUserBundle user entity, I'm skipping unique validation and catching a `Doctrine\DBAL\Exception\UniqueConstraintViolationException`.
In testing, this is failing, e.g. the exception is not caught.
If I try switching to a more general `Doctrine\DBAL\DBALException`, it looks like the exception is caught, anyway as soon as  a query is performed I'm getting this:
`SQLSTATE[25P02]: In failed sql transaction: 7 ERROR: current transaction is aborted, commands ignored until end of transaction block `

**Comment by dmaicher** [comment]
Interesting. The only place where I catch an exception is this:

https://github.com/dmaicher/doctrine-test-bundle/blob/master/src/DAMA/DoctrineTestBundle/Doctrine/DBAL/StaticDriver.php#L95

But that should not make any difference I think. Can you try commenting that out?

**Comment by garak** [comment]
No luck. Same exception.

**Comment by dmaicher** [comment]
Ok I will try to reproduce this tonight ;)

What would be interesting to know: How is the performance boost due to the `StaticArrayCache` for your testsuite? So if you just disable the static connection?

**Comment by garak** [comment]
As I told in #7, if I disable static connection it looks like no rollback is performed, so tests are failing.
Anyway, with everything active (and with unique check tests marked incomplete) my test suite halved time

**Comment by dmaicher** [comment]
Ok that's nice :) Thx for the info.

Will get back to you later regarding the `UniqueConstraintViolationException` issue.

**Comment by dmaicher** [comment]
Ok I can reproduce the problem with Mysql. You are using PostgreSQL?

Trying to figure out why this is happening.

**Comment by dmaicher** [comment]
Ok I found the issue for the missing exception of type `UniqueConstraintViolationException`.

Can you check how it goes with this? https://github.com/dmaicher/doctrine-test-bundle/pull/9

**Comment by garak** [comment]
Sorry, I forgot to mention that I'm using Postgres.
I'll try the code and I'll let you know. Thanks!

**Comment by dmaicher** [comment]
And any luck? :)

The `7 ERROR: current transaction is aborted, commands ignored until end of transaction block` has to be solved with a rollback then I guess if it still happens. In that regard Postgres behaves a bit different than Mysql.

**Comment by garak** [comment]
Sorry for the late reply, I had to revert my project to an old commit (since now I got rid of the ugly Exception catching and I'm using a "real" validation).
I tried with the new code and it looks like it's working. Thank you!

**Comment by dmaicher** [comment]
:+1:
