### ISSUE TITLE
Is there any way to start and rollback transaction in browser tests?

### ISSUE THREAD

**Issue by cve** [dmaicher/doctrine-test-bundle#83]
Hi,

I want to run my behat (chromedriver) tests within transaction and my question is: is that possible for example throught api endpoints?: /api/start-transaction and /api/rollback-transaction

**Comment by dmaicher** [comment]
This is not so easy to achieve :wink: 

If you execute php via a webserver you will get a new mysql connection on every request. So having a "cross-request transaction" is not really supported out-of-the box.

It might be doable with persistent connections? Never looked into it.

https://php.net/manual/en/features.persistent-connections.php

**Comment by dmaicher** [comment]
Anyway nothing I can fix on this bundle as it has to be supported lower level to have a persistent connection.

**Comment by cve** [comment]
Thank you for open my eyes on persistent connection :)
