### ISSUE TITLE
Deprecations

### ISSUE THREAD

**Issue by garak** [dmaicher/doctrine-test-bundle#88]
Spotted a new couple of deprecations related to PHPUnit:

>The "DAMA\DoctrineTestBundle\PHPUnit\PHPUnitListener" class implements "PHPUnit\Framework\TestListener" that is deprecated Use the `TestHook` interfaces instead.

and

>The "DAMA\DoctrineTestBundle\PHPUnit\PHPUnitListener" class uses "PHPUnit\Framework\TestListenerDefaultImplementation" that is deprecated The `TestListener` interface is deprecated.

**Comment by dmaicher** [comment]
@garak when do you get those deprecations? which phpunit version are you using?

**Comment by garak** [comment]
Sorry, it's my fault.
I was on a new project and likely I copied configuration from a very old one, using listener instead of extension with phpunit 8.
Thank you
